# nushell behavior (mirrors bash/aliases.bash + shell init)
# aliases, editor, starship prompt, zoxide — sourced after $env.config exists

# aliases (keep in sync with bash/aliases.bash)
alias ls = eza
alias ll = eza -lah
alias lt = eza --tree
alias la = eza -a
alias lg = eza -l --git
alias tg = topgrade

# editor / banner
$env.config.buffer_editor = "hx"
$env.config.show_banner = false

# theme (Tokyo Night color_config for nushell UI; terminal palette via ghostty/zellij)
source ./themes/tokyo-night.nu

# starship prompt (init file generated by script/bootstrap, then sourced)
# note: `source` resolves at parse time, so the .nu file must already exist here
source ./starship-init.nu

# zoxide (smart cd) — hooks via export-env, needs $env.config present
source ./zoxide.nu

# fix zoxide v0.10 nushell init: its `...rest: directory` type path-expands
# fuzzy terms (e.g. `z dotfiles` becomes cwd+dotfiles), breaking fuzzy jump.
# Override with a `string`-typed version. `zi` already uses string and works.
def --env --wrapped __zoxide_z_fixed [...rest: string] {
  let path = match $rest {
    [] => { `~` }
    [ `-` ] => { `-` }
    [ $arg ] if (($arg | path expand | path type) == dir) => { $arg }
    _ => { ^zoxide query --exclude $env.PWD -- ...$rest | str trim -r -c "\n" }
  }
  cd $path
}
alias z = __zoxide_z_fixed
