# nushell behavior (mirrors bash/aliases.bash + shell init)
# aliases, editor, starship prompt, zoxide — sourced after $env.config exists

# PATH hygiene: collapse inherited duplicates from a polluted parent. Runs here
# (not only in env.nu) because config.nu reliably loads on every REPL start.
# At config load the inherited PATH is a raw string (ENV_CONVERSIONS run after the
# config files), so normalize via `split row ":"` before the list dedupe; `uniq` is
# global distinct and preserves first-occurrence order.
$env.PATH = (
    (if ($env.PATH | describe | str starts-with "string") {
        $env.PATH | split row ":"
      } else {
        $env.PATH
      })
    | where {|e| $e != ""}
    | uniq
    | str join ":"
)

# aliases (keep in sync with bash/aliases.bash)
alias ls = eza
alias ll = eza -lah
alias lt = eza --tree
alias la = eza -a
alias lg = eza -l --git
alias tg = topgrade

# yank (binary ships as yank-cli — bash/aliases.bash parity) — pick a line, copy via wl-copy;
# your own `-- CMD` overrides the default copy command. `--wrapped` lets a standalone `--`
# reached the prompt reach $args (nushell treats `--` as an empty flag otherwise); def (not
# alias) because it must inject `-- wl-copy` conditionally and forward stdin ($in).
def --wrapped yank [...args: string] {
    let input = $in
    let target = if "--" in $args { $args } else { [...$args "--" "wl-copy"] }
    if (($input | describe) == "nothing") {
        ^yank-cli ...$target
    } else {
        $input | ^yank-cli ...$target
    }
}

# editor / banner
$env.config.buffer_editor = "hx"
$env.config.show_banner = false

# theme (Tokyo Night color_config for nushell UI; terminal palette via ghostty/zellij)
source ./themes/tokyo-night.nu

# starship prompt (init file generated by script/bootstrap, then sourced)
# note: `source` resolves at parse time, so the .nu file must already exist here
source ./starship-init.nu

# zoxide (smart cd) — hooks via export-env, needs $env.config present
source ./zoxide.nu

# fix zoxide v0.10 nushell init: its `...rest: directory` type path-expands
# fuzzy terms (e.g. `z dotfiles` becomes cwd+dotfiles), breaking fuzzy jump.
# Override with a `string`-typed version. `zi` already uses string and works.
def --env --wrapped __zoxide_z_fixed [...rest: string] {
  let path = match $rest {
    [] => { `~` }
    [ `-` ] => { `-` }
    [ $arg ] if (($arg | path expand | path type) == dir) => { $arg }
    _ => { ^zoxide query --exclude $env.PWD -- ...$rest | str trim -r -c "\n" }
  }
  cd $path
}
alias z = __zoxide_z_fixed
