# directories & state
music_directory     "/home/ghost_user/strata/30-39_media/32_audio"
db_file             "~/.cache/mpd/database"
log_file            "~/.cache/mpd/log"
sticker_file        "~/.cache/mpd/sticker.db"
playlist_directory  "~/.config/mpd/playlists"
state_file          "/run/user/1000/mpd.state"
pid_file            "/run/user/1000/mpd.pid"

# audio output
audio_output {
    type            "pipewire"
    name            "PipeWire"
}

# connection
bind_to_address     "localhost"
port                "6600"
